### ISSUE TITLE
ImportError: /OICR-pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by UT-Mao** [jd730/OICR-pytorch#10]
I met an Error when I ran the trainval_net.py, which said
ImportError: /OICR-pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

**Comment by UT-Mao** [comment]
Traceback (most recent call last):
  File "trainval_net.py", line 31, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/home/OICR-pytorch/lib/model/utils/net_utils.py", line 12, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/OICR-pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/OICR-pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/OICR-pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

**Comment by jd730** [comment]
It seems that roi_crop make file is not correctly generated. Which GPU are you using? Did you set -arch on [`make.sh`](https://github.com/jd730/OICR-pytorch/blob/cf203436a163bc96ab8a0a923770d34a8f2ddb80/lib/make.sh#L15) following ReadMe?

By the way, OICR actually does not use roi_crop, you can simply delete related lines.

**Comment by UT-Mao** [comment]
Thank you for your answer,
The problem has been solved, The reason is the version of my cuda didn't match the torch.
Thank you again :)
