### ISSUE TITLE
Issues about the flipped rois

### ISSUE THREAD

**Issue by XuYunqiu** [jd730/OICR-pytorch#12]
Hi, 
thanks for sharing your OICR implementation. I have some code issues about the **flip test**.

https://github.com/jd730/OICR-pytorch/blob/c519db015bda3c1a5254fad7f1d089197436b6ab/test_oicr.py#L216-L217
I think the blobs['data'][i] has a shape of [batch, H, W, 3], and the width should be obtained from blobs['data'][i].shape[2]. Is that correct?

**Comment by jd730** [comment]
You're right. I forgot to commit it after fixing a bug.

Thank you so much.
