### ISSUE TITLE
The result of my  mAP is very low

### ISSUE THREAD

**Issue by fregulationn** [jd730/OICR-pytorch#17]
In my  training process, I use the run.sh as below:
```
CUDA_VISIBLE_DEVICES=2  python trainval_net_org.py --dataset pascal_voc --net vgg16 \
   --bs 2 --nw 8 --save_dir=results/test_single_9  \
   --lr 0.001 --cuda --disp_interval 100 --vis \
	--checkpoint_interval=5000 --model='oicr' --threshold=0.1

CUDA_VISIBLE_DEVICES=2 python test_oicr.py --dataset pascal_voc --net vgg16  --checkpoint 070000 --load_dir=results/test_single_9 --cuda --output_dir="test" --model="oicr" --vis
```
the GPU is TiTan V, pytroch version is 0.4.0
But I get the AP result like this :
![image](https://user-images.githubusercontent.com/20834759/74587731-3883c200-5031-11ea-8d6d-d69cfea1a28f.png)
I haven't found the reason yet.

**Comment by jd730** [comment]
Hi @fregulationn 
could you tell me what `trainval_net_org.py` is? Is it same as original `trainval_net.py`?

Also did you run on the latest version?

(I am sorry that I mistakenly touched close issue button on my smartphone.)

**Comment by fregulationn** [comment]
the trainval_net_org.py is same as trainval_net.py
I download the code by  `git clone git:://github.com/jd730/OICR-pytorch.git`

thanks for your answer,my server is offline，so I can't have a try.
I will try your suggestion in feature.
