### ISSUE TITLE
My result of map is 0.2356，dataset is VOC2007，I didn't change the code，this is why？help.

### ISSUE THREAD

**Issue by ashencode** [jd730/OICR-pytorch#20]
My result of map is 0.2356，dataset is VOC2007，I didn't change the code，this is why？help.
sofa ap: 0.12975247981011617
cat ap: 0.01879150012978754
pottedplant ap: 0.20625525393691832
train ap: 0.5004305709273787
aeroplane ap: 0.2474352381104394
dog ap: 0.0289142347889386
bicycle ap: 0.3126646265085514
tvmonitor ap: 0.5629137748687733
person ap: 0.02026650342161751
car ap: 0.44308816282035074
sheep ap: 0.32254964068156194
bus ap: 0.5162746762903689
bird ap: 0.13202707092855498
motorbike ap: 0.5910886389691948
bottle ap: 0.05152223720911757
horse ap: 0.05455088120480837
cow ap: 0.2397996902710858
diningtable ap: 0.004031905442788624
boat ap: 0.14813410699849647
chair ap: 0.18177460452319866
I guess I have the same problem with @fregulationn.

**Comment by jd730** [comment]
Hi @ashencode,
Sorry for the late reply. I tested current version and original version of code 
 2f483b5491b716982bccf14eac7c09e0a7842275.
I found that refactoring and fixed miscellaneous bugs caused by refactoring yield bad performance you and @fregulationn mentioned.

I will change the code within this week. If you are urgent, please use 2f483b5491b716982bccf14eac7c09e0a7842275 version attaching nms_cuda.c (5ab65fd8090810cfbd4133ea1af5b95126505201)  which is omitted on that commit.

**Comment by jd730** [comment]
Using 2f483b5,
I recently achieved 
```
AP for aeroplane = 0.5935
AP for bicycle = 0.6014
AP for bird = 0.3659
AP for boat = 0.2322
AP for bottle = 0.1603
AP for bus = 0.6238
AP for car = 0.6143
AP for cat = 0.3930
AP for chair = 0.1409
AP for cow = 0.4830
AP for diningtable = 0.4137
AP for dog = 0.3960
AP for horse = 0.3300
AP for motorbike = 0.6498
AP for person = 0.1271
AP for pottedplant = 0.2164
AP for sheep = 0.4155
AP for sofa = 0.4930
AP for train = 0.5285
AP for tvmonitor = 0.5898
Mean AP = 0.4184
```

Thank you.

**Comment by ashencode** [comment]
Thanks very much，I'll try immediately.

**Comment by jd730** [comment]
Hi, @ashencode 
I found the reason. It was because the default pooling mode was `align` which degrades the performance. See https://github.com/jd730/OICR-pytorch/issues/13

https://github.com/jd730/OICR-pytorch/blob/286d6e9f6afe33f4e40c91c06db680d97d0e5fa2/cfgs/vgg16.yml#L13

**Comment by ashencode** [comment]
> Using [2f483b5](https://github.com/jd730/OICR-pytorch/commit/2f483b5491b716982bccf14eac7c09e0a7842275),
> I recently achieved
> 
> ```
> AP for aeroplane = 0.5935
> AP for bicycle = 0.6014
> AP for bird = 0.3659
> AP for boat = 0.2322
> AP for bottle = 0.1603
> AP for bus = 0.6238
> AP for car = 0.6143
> AP for cat = 0.3930
> AP for chair = 0.1409
> AP for cow = 0.4830
> AP for diningtable = 0.4137
> AP for dog = 0.3960
> AP for horse = 0.3300
> AP for motorbike = 0.6498
> AP for person = 0.1271
> AP for pottedplant = 0.2164
> AP for sheep = 0.4155
> AP for sofa = 0.4930
> AP for train = 0.5285
> AP for tvmonitor = 0.5898
> Mean AP = 0.4184
> ```
> 
> Thank you.

In this code，POOLING_MODE: align ，get a reasonable result.Can I further improve the performance by changing the  POOLING_MODE to pool？

**Comment by jd730** [comment]
Hi @ashencode ,
It depends on which version did you use. In some version, I manually set to use pool in  https://github.com/jd730/OICR-pytorch/blob/bcfe9cd2d7ab77fc46bc031da8fd27bd9971d57d/lib/model/oicr/oicr.py#L85

I think you are using that version.
