### ISSUE TITLE
A question about your code

### ISSUE THREAD

**Issue by lzrrr33** [jd730/OICR-pytorch#24]
hi bor ,thank you for sharing your code!
when i read your code,i have a question:
on line 124 of the /OICR-pytorch/lib/model/oicr/oicr.py , according to the paper, "self.ic_prob" should denote the proposal score matrices, but in your code, it seem like denote the classification score matrices.  I don’t understand it,hope for your reply

**Comment by jd730** [comment]
Hi @lzrrr33,
`ic_prob` is a classification score for each proposal in the paper. Please see Eq. (5), refinement loss.

**Comment by lzrrr33** [comment]
thank you for your reply !
but the item in `self.mdin_prob` is much lower than in `self.ic_prob` . this leads to the `cls_loss_weight` of ic0 lower than ic1 and ic2, is it normal?

**Comment by jd730** [comment]
Hi @lzrrr33,
Sorry about the late reply. I actually do not remember the scale of probs but what I remember is the losses from refinement branches are much lower than MIDN branch.

**Comment by lzrrr33** [comment]
thanks，sorry to bother you
