### ISSUE TITLE
Torch

### ISSUE THREAD

**Issue by XuanX-new** [jd730/OICR-pytorch#27]
Sorry to bother you. I have the followed question.
Found GPU0 GeForce RTX 2080 Ti which requires CUDA_VERSION >= 9000 for optimal performance and fast startup time, but your PyTorch was compiled with CUDA_VERSION 8000. My Configuration is torch 0.4.0+cuda9.0+torchvision0.2.2.

**Comment by jd730** [comment]
Hi @xiexuan1117, the reason why I implemented on torch 0.40 is to use compiled roi_pool. So, I guess that you can use torchvision's roi pooling with higher version of torch.

**Comment by XuanX-new** [comment]
Thank you for your suggestion. I will try it. 
Have a nice weekend!
| |
谢旋
|
|
xiexuan1117@163.com
|
签名由网易邮箱大师定制
On 12/12/2020 09:08，Jaedong Hwang<notifications@github.com> wrote：

Hi @xiexuan1117, the reason why torch version is 0.40 is to use compiled roi_pool. So, I guess that you can use torchvision's roi pooling with higher version of torch.

**Comment by jd730** [comment]
FYI, please refer to  https://github.com/jd730/OICR-pytorch/issues/8#issuecomment-653499183

**Comment by XuanX-new** [comment]
Sorry to bother you again. I have the follow issue.
 File "/home/summer/anaconda3/envs/OICR/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
Do you know the reason for this？My Configuration is pytorch 0.4.0+cuda9.0+torchvision0.2.1.

**Comment by jd730** [comment]
Hi @xiexuan1117,  which GPU are you using? If I remember correctly,  after GTX 20XX, Nvidia GPUs do not support torch 0.4

**Comment by XuanX-new** [comment]
ok，I see. The problem is that you say.The GPU is 2080 Ti that can‘t support torch 0.4. Thank you very much.
