### ISSUE TITLE
please give me the conda list or pip list, thankyou

### ISSUE THREAD

**Issue by junzai0215** [jd730/OICR-pytorch#31]
I met some build problems when I run the project. I think it is the env problem, thanks.

**Comment by jd730** [comment]
Hi @junzai0215, I actually delete my conda. Could you present to me which errors occurred?

Did you run [make.sh](https://github.com/jd730/OICR-pytorch/blob/master/lib/make.sh)? Did you install torch==0.4.0?

**Comment by jd730** [comment]
I guess below are my env.
```
argh            0.26.2
blessings       1.7
certifi         2018.8.24
cffi            1.11.5
chardet         3.0.4
Click           7.0
cloudpickle     0.7.0
configparser    4.0.2
cycler          0.10.0
Cython          0.29.5
dask            1.1.1
decorator       4.3.2
docker-pycreds  0.4.0
easydict        1.9
gitdb2          2.0.6
GitPython       3.0.5
gpustat         1.0.0.dev0
gql             0.2.0
graphql-core    2.2.1
idna            2.8
imageio         2.3.0
kiwisolver      1.0.1
matplotlib      3.0.0
mkl-fft         1.0.9
mkl-random      1.0.1
msgpack         0.6.1
networkx        2.2
numpy           1.15.2
nvidia-ml-py3   7.352.0
olefile         0.46
opencv-python   4.0.0.21
pathtools       0.1.2
Pillow          5.2.0
pip             19.0.2
promise         2.3
protobuf        3.6.1
psutil          5.6.7
pycocotools     2.0.0
pycparser       2.19
pydensecrf      1.0rc3
pyparsing       2.3.1
python-dateutil 2.8.0
pytz            2018.9
PyWavelets      1.0.1
PyYAML          3.13
requests        2.22.0
Rx              1.6.1
scikit-image    0.14.0
scikit-learn    0.20.2
scipy           1.2.1
sentry-sdk      0.13.5
setuptools      40.2.0
shortuuid       0.5.0
six             1.11.0
sklearn         0.0
smmap2          2.0.5
subprocess32    3.5.4
tensorboardX    1.6
toolz           0.9.0
torch           0.4.0
torchvision     0.2.1
tornado         5.1.1
tqdm            4.41.1
urllib3         1.25.7
wandb           0.8.19
watchdog        0.9.0
wheel           0.31.1
xmltodict       0.12.01
```

**Comment by junzai0215** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jd730/OICR-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月18日(星期天) 上午8:31
***@***.***&gt;;
抄送:&nbsp;"Wenjun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jd730/OICR-pytorch] please give me the conda list or pip list, thankyou (#31)





 
I guess below are my env.
 argh            0.26.2 blessings       1.7 certifi         2018.8.24 cffi            1.11.5 chardet         3.0.4 Click           7.0 cloudpickle     0.7.0 configparser    4.0.2 cycler          0.10.0 Cython          0.29.5 dask            1.1.1 decorator       4.3.2 docker-pycreds  0.4.0 easydict        1.9 gitdb2          2.0.6 GitPython       3.0.5 gpustat         1.0.0.dev0 gql             0.2.0 graphql-core    2.2.1 idna            2.8 imageio         2.3.0 kiwisolver      1.0.1 matplotlib      3.0.0 mkl-fft         1.0.9 mkl-random      1.0.1 msgpack         0.6.1 networkx        2.2 numpy           1.15.2 nvidia-ml-py3   7.352.0 olefile         0.46 opencv-python   4.0.0.21 pathtools       0.1.2 Pillow          5.2.0 pip             19.0.2 promise         2.3 protobuf        3.6.1 psutil          5.6.7 pycocotools     2.0.0 pycparser       2.19 pydensecrf      1.0rc3 pyparsing       2.3.1 python-dateutil 2.8.0 pytz            2018.9 PyWavelets      1.0.1 PyYAML          3.13 requests        2.22.0 Rx              1.6.1 scikit-image    0.14.0 scikit-learn    0.20.2 scipy           1.2.1 sentry-sdk      0.13.5 setuptools      40.2.0 shortuuid       0.5.0 six             1.11.0 sklearn         0.0 smmap2          2.0.5 subprocess32    3.5.4 tensorboardX    1.6 toolz           0.9.0 torch           0.4.0 torchvision     0.2.1 tornado         5.1.1 tqdm            4.41.1 urllib3         1.25.7 wandb           0.8.19 watchdog        0.9.0 wheel           0.31.1 xmltodict       0.12.01
