### ISSUE TITLE
ModuleNotFoundError: No module named 'model.utils.cython_bbox'

### ISSUE THREAD

**Issue by zwyyy215** [jd730/OICR-pytorch#5]
Hello, I have a new question，I tried to solve it by myself, but I failed.
(OICR) mickey@a208-System-Product-Name:~/OICR-pytorch$ CUDA_VISIBLE_DEVICES=0 python3 trainval_net.py --dataset pascal_voc --net vgg16 \
>    --bs 2 --nw 6 --save_dir='results/test_single'  \
>    --lr 0.001 --cuda --disp_interval 50 --vis \
>         --checkpoint_interval=500 --model='oicr' --threshold=0.1
Traceback (most recent call last):
  File "trainval_net.py", line 28, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/mickey/OICR-pytorch/lib/roi_data_layer/roidb.py", line 15, in <module>
    import model.utils.cython_bbox
ModuleNotFoundError: No module named 'model.utils.cython_bbox'

**Comment by jd730** [comment]
Hi, did you run `make.sh` which is in `lib` folder?
`make.sh` installs that file using [this](https://github.com/jd730/OICR-pytorch/blob/de8a960377924f7a6bd5821ba7bffe2b28d4c302/lib/setup.py#L117)

**Comment by zwyyy215** [comment]
I know why, after my first successful run, that file was deleted by me, so I had to run make.sh  file again. I'm too careless. Thank you for your patient guidance.
