### ISSUE TITLE
Function of this file：cmap.py

### ISSUE THREAD

**Issue by zwyyy215** [jd730/OICR-pytorch#7]
I'm a beginner. I want to ask what the function of this function is.、
camp.py
Thank you!

**Comment by jd730** [comment]
Hi, this function is used for colorization of segmentation task which means that it is not used in this repo. 
I will delete right now. I apologize for the inconvenience.

**Comment by jd730** [comment]
Commit: cf203436a163bc96ab8a0a923770d34a8f2ddb80

**Comment by zwyyy215** [comment]
Thank you very much.
