### ISSUE TITLE
Where is data folder？should I create one？

### ISSUE THREAD

**Issue by UT-Mao** [jd730/OICR-pytorch#9]
As the readme said that
 creat softlinks in the folder data/.
move selective_search_data folder into data folder.
But there is no folder named data. should I creat a folder and name it "data" ?

**Comment by jd730** [comment]
@Moukahou, Yes you need to create a data folder and its subdirectories.
You can download the data following [this](https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models).

the directory structure is as follows

OICR-pytorch/data/VOCdevkit2007
OICR-pytorch/data/VOCdevkit2012
OICR-pytorch/data/selective_search_data

**Comment by UT-Mao** [comment]
Thank you ！
